#!/bin/sh
set -e

MY_IP=${MY_IP:=$(hostname -I | awk '{print $1}')}
MY_DOMAIN=${MY_DOMAIN:=$(hostname)}
WS_PORT=${WS_PORT:=8080}
WSS_PORT=${WSS_PORT:=8443}

sed -i -e "s/FILL_MY_IP/${MY_IP}/g" /etc/rtpengine/rtpengine.conf
sed -i -e "s/FILL_MY_IP/${MY_IP}/g" /etc/kamailio/kamailio.cfg
sed -i -e "s/FILL_MY_IP/${MY_IP}/g" /healthcheck

sed -i -e "s/FILL_MY_DOMAIN/${MY_DOMAIN}/g" /etc/kamailio/kamailio.cfg
sed -i -e "s/FILL_MY_DOMAIN/${MY_DOMAIN}/g" /etc/kamailio/kamctlrc

sed -i -e "s/FILL_WS_PORT/${WS_PORT}/g" /etc/kamailio/kamailio.cfg
sed -i -e "s/FILL_WSS_PORT/${WSS_PORT}/g" /etc/kamailio/kamailio.cfg

# Allow disabling TLS by setting the TLS_DISABLE env variable to true
if [ "$TLS_DISABLE" = "true" ] || [ "$TLS_DISABLE" = "1" ]
then
  sed -i -e "s/#!define WITH_TLS/##!define WITH_TLS/" /etc/kamailio/kamailio.cfg
else
  chown kamailio:kamailio -R /etc/ssl/kamailio
  chmod 755 /etc/ssl/kamailio
  chmod 744 /etc/ssl/kamailio/fullchain.pem
  chmod 700 /etc/ssl/kamailio/privkey.pem
fi

# shellcheck disable=SC2068
exec $@
